config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
resources :flats
root to: 'flats#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_card.html.erb
<div class="col-4">
      <div class="card shadow p-3 mb-5 bg-white rounded" style="min-height: 15rem ">
        <div class="card-body">
          <h5 class="card-title text-center"><%= flat.name %></h5>
          <p class="card-text"><%= flat.description %>.</p>
          <div id="icons" class="d-flex justify-content-center" style="gap: 50px">
            <div>
              <i class="fa-solid fa-sterling-sign"> <%= flat.price_per_night %></i>
            </div>
            <div>
              <i class="fa-solid fa-person-walking-luggage"> <%= flat.number_of_guests %></i>
            </div>
          </div>
          <div class="d-flex justify-content-center" style="margin-top: 10px">
            <a href="/" class="btn btn-primary ">Go to listing</a>
          </div>
        </div>
      </div>
    </div>

app/views/flats/_navbar.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="<%= flats_path%>" style="margin-left: 10px">Simple Airbnb</a>
  <a class="btn btn-outline-primary" href="<%= new_flat_path %>" style="margin-right: 10px">Add a flat</a>
</nav>

app/views/flats/index.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="/" style="margin-left: 10px">Simple Airbnb</a>
  <form class="form-inline">
    <button class="btn btn-outline-primary" type="button" href="/index" style="margin-right: 10px">All Listings</button>
  </form>
</nav>
<div class="container">
  <h1>Showing all available listings! (<%= @flats.count %>)</h1>
  <hr>
  <div class="row">
  <% @flats.each do |flat| %>
    <div class="col-4">
      <div class="card shadow p-3 mb-5 bg-white rounded" style="min-height: 15rem ">
        <div class="card-body">
          <h5 class="card-title text-center"><%= flat.name %></h5>
          <p class="card-text"><%= flat.description %>.</p>
          <div id="icons" class="d-flex justify-content-center" style="gap: 50px">
            <div>
              <i class="fa-solid fa-sterling-sign"> <%= flat.price_per_night %></i>
            </div>
            <div>
              <i class="fa-solid fa-person-walking-luggage"> <%= flat.number_of_guests %></i>
            </div>
          </div>
          <div class="d-flex justify-content-center" style="margin-top: 10px">
            <a href="/" class="btn btn-primary ">Go to listing</a>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= render "navbar" %>

<div class="container">
  <h1>Add a new flat!</h1>
  <hr>
  <div class="h-100 d-flex align-items-center justify-content-center card shadow p-3 mb-5 bg-white rounded">
    <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night, as: :integer, input_html: { min: '0', max: '999', step: 'any'}%>
    <%= f.input :number_of_guests, as: :integer, input_html: { min: '0', max: '5', step: '1'}%>
    <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<%= render "navbar" %>

<div class="container">
  <div class="h-100 d-flex align-items-center justify-content-center card shadow p-3 mb-5 bg-white rounded">
    <h2><%= flat.name %></h2>
    <hr>
    <p><%= flat.address %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>